### ISSUE TITLE
BJA- publication: Practical approach to lung ultrasound

### ISSUE THREAD

**Issue by LauramzyMD** [jannisborn/covid19_pocus_ultrasound#14]
Great approach and publication on ultrasound findings and diagnostics. This paper highlights urgent-care and critical-care diagnostic approaches for improved diagnostic accuracy.  

Lung ultrasound (LU) relies on direct visualization of structures and artifact interpretation.
A curvilinear probe is the best ‘all-rounder’.
LU has a very high diagnostic accuracy.
A comprehensive point-of-care scan can be done in <5 min.
A training structure and competencies specific to critical care in the UK have been developed.

https://academic.oup.com/bjaed/article/16/2/39/2897763

**Comment by jannisborn** [comment]
This is a great source!
There's even a video in there. We should add the data to our database soon, so I added the respective labels.

**Comment by NinaWie** [comment]
I took three videos from this article, will add to database
