### ISSUE TITLE
1 image per class

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#18]
https://link.springer.com/content/pdf/10.1007/s00247-017-3910-1.pdf

- Fig1: ealthy image
- Fig2: B-lines and interstinal patterns (indicate for viral pneumonia, but this is not COVID since it's old)
- Fig3: Seems like bacterial pneumonia (air bronchograms)

questionable to use since there is artifacts.

**Comment by NinaWie** [comment]
I took out the images, many arrows though
