### ISSUE TITLE
4 videos plus a few images

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#19]
https://theultrasoundjournal.springeropen.com/articles/10.1186/2036-7902-4-16

There is 4 videos in this publication!
- All linear probes
- 2x viral pneumonia (not COVID)
- 1x bacterial pn.
- 1x symptoms of both

- Several images (but contain a lot of artifacts)

**Comment by NinaWie** [comment]
done - good linear probes
