### ISSUE TITLE
4 images from children with COVID-19 with artifacts

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#2]
https://pediatrics.aappublications.org/content/pediatrics/early/2020/04/17/peds.2020-1157.full.pdf

Images have artifacts/arrows

**Comment by NinaWie** [comment]
Linear probes, lots of artifacts and bad quality - not sure it's worth it

**Comment by jannisborn** [comment]
Closing due to insufficient quality.
