### ISSUE TITLE
A few images

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#21]
https://www.sciencedirect.com/science/article/pii/S0720048X16304260?casa_token=b8FWvdm_EkAAAAAA:H31to1wr9OoD-yRrZsfmFuEmRk06uoQJ_o4ig4VgtRb95U8PYuPzLc_2TzrnScnV81Gwd-bfcKE#fig0005

Not super sure on bacterial vs viral pneumonia. Linear probes
4 images in total, not sure on quality.

**Comment by NinaWie** [comment]
I think it's all bacterial pneumonia. Downloaded them. artefacts in two of them
