### ISSUE TITLE
10 videos!

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#22]
https://www.sciencedirect.com/science/article/pii/S0733862715000772#mmc1

- 10 videos in total just in one publication :)
- convex and linear probes
- class labels are not always clear but there are definitely a few healthy and a few bacterial pneumonia. Little to no artifacts.

**Comment by NinaWie** [comment]
Downloaded, cropped and processed 4 videos, probably the other ones are not usable (pneumothorax etc) - will check with our medical people whether any other can be used
