### ISSUE TITLE
Update butterfly data

### ISSUE THREAD

**Issue by NinaWie** [jannisborn/covid19_pocus_ultrasound#24]
They also have a site with just lung ultrasound images https://www.butterflynetwork.com/de/clinical/lung 

I haven't compared the videos in their Covid gallery https://butterflynetwork.getbynder.com/transfer/2cf9af2398bdc35b6b0d2100180cb69580198f41faeb4c25d9cdae61d1ca8e91 to the ones we have, but I think we should check again because they uploaded new data probably and it would be nice to use it

**Comment by jannisborn** [comment]
we should attempt a `.sh` script to parse the data automatically.

**Comment by jannisborn** [comment]
Closing since the videos only show patterns but classification is unknown.
