### ISSUE TITLE
Sonosite Data

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#30]
2 more videos:

- https://www.youtube.com/watch?time_continue=3&v=mtcEyaDGh8U&feature=emb_logo (COVID)
- https://www.youtube.com/watch?time_continue=7&v=5Ozz6gMmZmg&feature=emb_logo (Pneumonia)

Probably not licensed.  We can ask whether we can redistribute.
More data may be here: https://de.secure.sonosite.com/COVID-19

**Comment by NinaWie** [comment]
Quality is very bad and probably we can't redistribute. Wouldn't use it
