### ISSUE TITLE
8 COVID-19 videos from pregnant women

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#32]
I was pointed to this publication: https://onlinelibrary.wiley.com/doi/full/10.1002/jum.15367

- 8 pregnant women with COVID (confirmed by PCR)
- 8 videos available (see supplementary)
- data seems high quality but requires manual cropping
- a lot of metadata on all patients, e.g. visible patterns, availiability of CT/CXR, age, gender etc.

-> First author would like to be mentioned in our repo (with his article).
-> We could create a section with papers from which we got data :) 

We could consider to collect meta-data too. If we featurize it properly, it could be valuable in the future.

**Comment by NinaWie** [comment]
Finished processing, will be added with next push
