### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [jannisborn/covid19_pocus_ultrasound#33]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data framehttp://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/46KAJH

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by jannisborn** [comment]
Hi,
Thanks for sharing the great news. We are happy to be part of that initiative and we can of course add meta-data about it on Dataverse. Could you maybe explain how we can help?

The main collecting point for this dataset should stay on Git though and not be outsourced to other websites (but I guess that's not the point of your project anyways, right?)

**Comment by k-goncharova** [comment]
Hello Jannis, thank you for your response and willingness to contribute. 

You're right, it's not the point to change the collecting point for your dataset. Adding it to Dataverse and synchronizing all updates from GitHub to Dataverse (implemented already) just helps to expose it to wider scientific community. 

At this point it would be also helpful, if you could add metadata (description, keywords) to your dataset in Dataverse.  Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the necessary permissions for editing your dataset.

Additionally, you may want join our community of 1,000+ contributors in Slack https://www.coronawhy.org/join-the-fight and see if any other initiatives could be interesting to you. We have many cool people and interesting things going on :)

**Comment by jannisborn** [comment]
Thanks @k-goncharova!
I just created an account (username: jannisborn). Could you please give me access to edit our dataset.

**Comment by k-goncharova** [comment]
Done!

**Comment by jannisborn** [comment]
Thanks @k-goncharova.
I added all the meta data now. I would like to change the citation. If I click on `Cite Dataset` -> `BibTex` the entry is:

```bib
@data{FK2/46KAJH_2020,
author = {Jannis Born},
publisher = {COVID-19 Data Hub},
title = "{PoCOVIDScreen - Lung Ultrasound data for COVID-19 (POCUS)}",
year = {2020},
version = {V2},
doi = {10.5072/FK2/46KAJH},
url = {https://doi.org/10.5072/FK2/46KAJH}
}
```

If people cite our dataset like this, Google Scholar will not be able to link it to our arXiv paper. Could you tell me how I can update it? The `bibtex` should be :
```bib
@article{born2020pocovid,
  title={POCOVID-Net: automatic detection of COVID-19 from a new lung ultrasound imaging dataset (POCUS)},
  author={Born, Jannis and Br{\"a}ndle, Gabriel and Cossio, Manuel and Disdier, Marion and Goulet, Julie and Roulin, J{\'e}r{\'e}mie and Wiedemann, Nina},
  journal={arXiv preprint arXiv:2004.12084},
  year={2020}
}
```

**Comment by jannisborn** [comment]
any update on this @k-goncharova @reeshmabijosh ?

**Comment by jannisborn** [comment]
any update on this @k-goncharova @reeshmabijosh ?

**Comment by k-goncharova** [comment]
Hello Jannis, Thanks for your patience while I was checking details with our tech team. Unfortunately, the citation format for datasets is just different for data compared to articles. You can see details here https://dataverse.org/best-practices/data-citation. 

At this point you have all the admin permissions for your dataset in Dataverse, feel free to proceed with any additional updates that are within standards allowed by Dataverse. 

If you might be unhappy with this and do not want to see your dataset in CoronaWhy Dataverse as it is now, please let me know and I'll proceed with dataset deaccession. 

Thank you.

**Comment by jannisborn** [comment]
Alright, many thanks @k-goncharova
