### ISSUE TITLE
6-7 videos

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#36]
Labels are not super clear (seems symptom based)

https://theultrasoundjournal.springeropen.com/articles/10.1186/s13089-020-00177-4#Sec8

**Comment by NinaWie** [comment]
Wrote the authors, waiting for information about videos 2-4. For others finished processing

**Comment by NinaWie** [comment]
Authors haven't replied, I have added three of the videos to the database, the other three are really unclear. I have downloaded them though

**Comment by NinaWie** [comment]
Sent a message again, will wait a bit more

**Comment by NinaWie** [comment]
Closing this issue because no reply of authors, we now only added the videos partly
