### ISSUE TITLE
14 COVID videos

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#38]
Plenty new COVID videos from [this paper](https://link.springer.com/article/10.1007%2Fs12630-020-01704-6#author-information).

Total of 14 COVID videos. Looks a bit heterogenous in light conditions etc.

I copy the symptoms below as listed in the paper.

**Those seem to be "standard" LUS-COVID findings (S1-S6)**
1. (A) B-lines (arrow)
2. (B) irregular and broken pleural lines with multiple B-lines (dotted region);
3. (C) peripheral or subpleural consolidation with 
4. (D) minimal colour Doppler signal. 
5. (E) Larger zone of consolidation in right lower posterior base with air bronchograms an
6. (F) reduced perfusion using colour Dopple

S7 is CT data

**S8 and S9 are COVID findings with additional complications:** (not sure we should use those -> ask MDs)
7. B) Transthoracic short-axis aortic valve view showing a dilated right ventricular outflow tract (RVOT) of 35 mm and pulmonary artery in a patient with pulmonary embolism. (video not available currently).
8. C) Deep venous thrombosis of the femoral vein.

**S10 - S15 is a COVID patient with severe hypotoxia**
9. - 11. before (A–C)
12.-14. after (D–F) prone positioning. Note the significant changes with loss of pleural fluid and consolidation with increased aeration. 
**Note that this is a single patient. If we take it, it should be in the same split**

**Comment by NinaWie** [comment]
added 6 videos, Gabriel commented all of them
