### ISSUE TITLE
2 Healthy & 5 COVID videos

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#39]
https://www.stemlynsblog.org/combatting-covid19-is-lung-ultrasound-an-option/

- 2 healthy videos
- 5 COVID videos

There seems to be a publication associated, however it doesn't seem published:
https://www.researchgate.net/publication/342215033_Combatting_COVID-19_Is_Ultrasound_an_Important_Piece_in_the_Diagnostic_Puzzle_Correspondence_to_Word_count_excluding_figures_in-text_references_bibliography

**Comment by NinaWie** [comment]
I added the 7 videos, but I open another issue with this website because there are nice further links to other educational websites that we should check out
