### ISSUE TITLE
~10 COVID-19 images

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#4]
https://link.springer.com/article/10.1007%2Fs40477-020-00458-7

Data looks rather clean, we have to check which ones to use.

**Comment by NinaWie** [comment]
Downloaded, nice quality, rarely any arrows - need to be checked by Gabriel

**Comment by jannisborn** [comment]
We may need to check the image-patient mapping.  If possible we should make sure that the same patient doesn't end up in different folds. I checked but cant infer from the manuscript text. Maybe the images by itself? Maybe the R_X at the bottom left? Or the CA_XX at the top left? Maybe Lotte/Gabriel knows  what these mean?

Worst case, we could reach out to the authors.
