### ISSUE TITLE
60 unlabled videos

### ISSUE THREAD

**Issue by TonyApril** [jannisborn/covid19_pocus_ultrasound#41]
From website 'https://www.disi.unitn.it/iclus', 60 videos can be obtained but they aren't labled.

**Comment by jannisborn** [comment]
Dear Tony,
Thanks for your interest in our work. 
This data is not part of our dataset and not under our control. That the labels for the ICLUS data are missing is a known issue (see [here](https://github.com/mhug-Trento/DL4covidUltrasound/issues/1)). This repo is not the right place for this issue, please contact the authors of the paper.

Here, we're creating an independent lung US dataset that is assembled from various websites and publications. The ICLUS dataset is for severity assessment, ours is for differential diagnosis. To date, our dataset is larger than what ICLUS released and ours is fully labelled with more data to come. The ICLUS data is not part of our dataset since we have by no means the right to re-distribute it..

**Comment by TonyApril** [comment]
Dear jannisborn,


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sorry, my mistake. Got it.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Considering what you have said, do you mean that the datesets in your project can be used directly in my research and paper?
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Or I have to be authorized by the original authors or someone else?


Best,
Tony




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jannis Born"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 下午2:12
收件人: "jannisborn/covid19_pocus_ultrasound"<covid19_pocus_ultrasound@noreply.github.com&gt;; 
抄送: "WRX"<907932614@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jannisborn/covid19_pocus_ultrasound] 60 unlabled videos (#41)





 
Dear Tony,
 Thanks for your interest in our work.
 This data is not part of our dataset and not under our control. That the labels for the ICLUS data are missing is a known issue (see here). This repo is not the right place for this issue, please contact the authors of the paper.
 
Here, we're creating an independent lung US dataset that is assembled from various websites and publications. The ICLUS dataset is for severity assessment, ours is for differential diagnosis. To date, our dataset is larger than what ICLUS released and ours is fully labelled with more data to come. The ICLUS data is not part of our dataset since we have by no means the right to re-distribute it..

**Comment by jannisborn** [comment]
Dear Tony,
No worries.
Yes, of course you can use the dataset in this repo directly for your research & paper. This is the intention of the dataset :) Just don't re-distribute it anywhere else.

And please give credits, at least in the form of a citation. Our paper is in peer-review, so please keep an eye on this repo. We'd update the `bibtex` when the paper is out. For the time being, please cite us as :

```bib
@article{born2020pocovid,
  title={POCOVID-Net: Automatic Detection of COVID-19 From a New Lung Ultrasound Imaging Dataset (POCUS)},
  author={Born, Jannis and Br{\"a}ndle, Gabriel and Cossio, Manuel and Disdier, Marion and Goulet, Julie and Roulin, J{\'e}r{\'e}mie and Wiedemann, Nina},
  journal={arXiv preprint arXiv:2004.12084},
  year={2020}
}
```

If you have any ideas for how to improve the models, please feel free to create a PR or open an issue. We're continuously working on this.

**Comment by TonyApril** [comment]
ok, good luck




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jannis Born"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 下午2:28
收件人: "jannisborn/covid19_pocus_ultrasound"<covid19_pocus_ultrasound@noreply.github.com&gt;; 
抄送: "WRX"<907932614@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jannisborn/covid19_pocus_ultrasound] 60 unlabled videos (#41)





 
Dear Tony,
 No worries.
 Yes, of course you can use the dataset in this repo directly for your research &amp; paper. This is the intention of the dataset :) Just don't re-distribute it anywhere else.
 
And please give credits, at least in the form of a citation. Our paper is in peer-review, so please keep an eye on this repo. We'd update the bibtex when the paper is out. For the time being, please cite us as :
 @article{born2020pocovid,   title={POCOVID-Net: Automatic Detection of COVID-19 From a New Lung Ultrasound Imaging Dataset (POCUS)},   author={Born, Jannis and Br{\"a}ndle, Gabriel and Cossio, Manuel and Disdier, Marion and Goulet, Julie and Roulin, J{\'e}r{\'e}mie and Wiedemann, Nina},   journal={arXiv preprint arXiv:2004.12084},   year={2020} }
 
If you have any ideas for how to improve the models, please feel free to create a PR or open an issue. We're continuously working on this.
