### ISSUE TITLE
about 'data_from_butterfly.json'

### ISSUE THREAD

**Issue by GCQiu** [jannisborn/covid19_pocus_ultrasound#61]
I would like to ask where is this file  'data_from_butterfly.json'

**Comment by GCQiu** [comment]
Dear Nina，
&nbsp; &nbsp; Hello，i didn't understand what you mean


Best，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jannisborn/covid19_pocus_ultrasound"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午4:16
收件人:&nbsp;"jannisborn/covid19_pocus_ultrasound"<covid19_pocus_ultrasound@noreply.github.com&gt;;
抄送:&nbsp;"WET"<99087974@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jannisborn/covid19_pocus_ultrasound] about 'data_from_butterfly.json' (#61)





 
Closed #61 via a4d558b.

**Comment by NinaWie** [comment]
Sorry for that, I added the file. It is in the [data folder](https://github.com/jannisborn/covid19_pocus_ultrasound/blob/master/data/data_from_butterfly.json).

**Comment by NinaWie** [comment]
If you want to process the data, run ```sh parse_butterfly.sh``` from the data folder. It will now find the file. Let me know if you have any more issues

**Comment by GCQiu** [comment]
Thank you so much for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jannisborn/covid19_pocus_ultrasound"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午4:47
收件人:&nbsp;"jannisborn/covid19_pocus_ultrasound"<covid19_pocus_ultrasound@noreply.github.com&gt;;
抄送:&nbsp;"WET"<99087974@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jannisborn/covid19_pocus_ultrasound] about 'data_from_butterfly.json' (#61)





 
If you want to process the data, run sh parse_butterfly.sh from the data folder. It will now find the file. Let me know if you have any more issues
