### ISSUE TITLE
Annotated Data

### ISSUE THREAD

**Issue by muditgarg94** [jannisborn/covid19_pocus_ultrasound#65]
I cannot find any file which annotates the given dataset. I appreciate if you can update the data with annotations or if it is there, would you please point out the file to me?

Thanks
Mudit

**Comment by jannisborn** [comment]
Hi Mudit,

Please note that the files are named according to their class label. Files starting with "Reg" show healthy lungs, "Cov" is for COVID-19 etc. 

If you were searching for region annotations to perform a segmentation task: those annotations are not available. 

I'm closing this, please reopen if applicable.
