### ISSUE TITLE
Data from Como (Pub)

### ISSUE THREAD

**Issue by jannisborn** [jannisborn/covid19_pocus_ultrasound#9]
DOI: 10.1016/j.ejro.2020.100231

https://www.sciencedirect.com/science/article/pii/S2352047720300204#fig0005

3 images in total, all COVID

1. Convex: [(A) shows the simultaneous co-existence of multiple lung B-lines and A-lines. ](https://ars.els-cdn.com/content/image/1-s2.0-S2352047720300204-gr1_lrg.jpg)
2. Convex: [patient with Coronavirus disease-19 shows compact B-line without horizontal reverberation (white lung sign), with tiny areas of subpleural consolidation.](https://ars.els-cdn.com/content/image/1-s2.0-S2352047720300204-gr2_lrg.jpg)
3. Linear: [ Ultrasound thoracic examination using a linear transducer of a Patient with Coronavirus disease-19 (A) shows the irregular appearance of the pleural line with multifocal B-line. ](https://ars.els-cdn.com/content/image/1-s2.0-S2352047720300204-gr3_lrg.jpg)

**Comment by NinaWie** [comment]
Downloaded, no artefacts, nice to have a description in the issue
